version: "3"
services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server-front:{FRONT_TAG}
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./BE
    env_file:
      - ./BE/.env/prod
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server:{BACK_TAG}
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENVIRONMENT: PROD