version: '3'
services:
  frontend:
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server-front:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

  backend:
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENV=production