version: "3"
services:
  backend:
    env_file:
      - .env
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENVIRONMENT=PROD