version: '3'
services:
  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server-front:latest
    ports:
      - "3000:3000"
    restart: always

  backend:
    build:
      context: ./BE
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server:latest
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENV=production