version: "3"
services:
  frontend:
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server-front:{FRONT_TAG}
    ports:
      - "3000:3000"
    restart: always

  backend:
    env_file:
      - .env
    image: 897729099078.dkr.ecr.ap-northeast-2.amazonaws.com/slam-server:{BACK_TAG}
    ports:
      - "8000:8000"
    restart: always
    environment:
      - ENVIRONMENT=PROD